Accounts/urls.py
from django.urls import path
from . import views 


app_name = 'Accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('edite_profile/', views.edite_profile, name='edite_profile'),

    
    
]

Contact/urls.py
from django.urls import path, include
from . import views 


app_name = 'Contact'
urlpatterns = [
    path('contact/', views.contact, name='contact'),
]

Job/urls.py
from django.urls import path,include
from . import views as v
from . import api

app_name='Job'
urlpatterns = [
    path('',v.job_list,name='job_list'),
    path('<int:id>/apply', v.apply, name='apply'),
    path('add-job', v.add_job, name='add_job'),
    path('api/jobs', api.Job_api_list, name='Job_api_list'), 
    path('api/jobs/<int:id>', api.job_detail_api, name='job_detail_api'),
    path('<int:id>', v.job, name='job'),
]

project/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('Accounts.urls', namespace='Accounts')),
    path('admin/', admin.site.urls),
    path('', include('Contact.urls', namespace='Contact')),
    path('api-auth/', include('rest_framework.urls')),
    path('',include('Job.urls',namespace='Job')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Accounts/models.py
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    first_name=models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    biographie=models.TextField()
    image=models.ImageField(upload_to='media/profile_images/')

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

Contact/models.py
from django.db import models

# Create your models here.

Job/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
# Create your models here.
Job_Type=[

    ('part time', 'part time'),
    ('full time', 'full time')
]


class Job(models.Model):
    owner=models.ForeignKey(User ,on_delete=models.CASCADE)
    title=models.CharField(max_length=200)
    description=models.TextField()
    image=models.ImageField(upload_to='media/images/')
    city = models.CharField(max_length=200)
    contry=models.CharField(max_length=200)
    job_type = models.CharField(max_length=10, choices=Job_Type)
    published_at=models.DateTimeField(auto_now_add=True)
    salary=models.IntegerField(default=0)
    slug = models.SlugField(null=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Job, self).save(*args, **kwargs)
    def __str__(self):
        return self.title


class Comment(models.Model):
    full_name=models.CharField(max_length=150)
    email=models.EmailField()
    comment=models.TextField()
    published_at=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.full_name




class Apply(models.Model):
    job = models.ForeignKey(Job,on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    email = models.EmailField()
    website = models.URLField(max_length=200)
    cv = models.FileField(upload_to='media/cv/')
    letter = models.TextField()
    apply_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

Accounts/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class signupform(UserCreationForm):
    class Meta:
        model = User
        fields=['username','password1','password2']

class profileform(forms.ModelForm):
    class Meta:
        model=Profile
        fields='__all__'
        exclude=('user',)

Job/forms.py
from django import forms
from .models import *

class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields='__all__'
        exclude=('owner','slug',)

class ApplyForm(forms.ModelForm):
    class Meta:
        model=Apply
        fields='__all__'
        exclude = ('job',)

class commentform(forms.ModelForm):
    class Meta:
        model=Comment
        firlds='__all__'
        exclude = ('published_at',)

Accounts/views.py
from django.shortcuts import redirect, render, get_object_or_404, reverse
from .forms import *
from django.contrib.auth import authenticate, login

from django.contrib.auth.decorators import login_required


# Create your views here.
def signup(request):
    if request.method=='POST':
        form=signupform(request.POST)
        
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            pas = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=pas)
            login(request, user)
            return redirect('/')
    else:
        form=signupform()
    context={
        'form':form,
    }
    return render(request,'signup.html',context)


@login_required(login_url="/accounts/login/")
def profile(request):
    p = get_object_or_404(Profile,user=request.user)
    context={
        'p':p,
    }

    return render(request,'profile.html',context)

@login_required
def edite_profile(request):
    p = get_object_or_404(Profile, user=request.user)
    if request.method=='POST':
        u_form = signupform(request.POST, request.FILES, instance=request.user)
        p_form=profileform(request.POST,request.FILES,instance=p)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('Accounts:profile')
    else:
        u_form = signupform(instance=request.user)
        p_form = profileform(instance=p)
    context={
        'u_form': u_form,
        'p_form':p_form,
    }
    return render(request, 'edite_profile.html', context)

Contact/views.py
from django.shortcuts import render


# Create your views here.
def contact(request):
    return render(request,'contact.html')

Job/views.py
from django.shortcuts import render,reverse, get_object_or_404, redirect
from .models import *
from .forms import *
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .filters import ProductFilter
# Create your views here.


def job_list(request):
    jobs = Job.objects.all().order_by('-published_at')
    filter = ProductFilter(request.GET, queryset=jobs)
    jobs=filter.qs
    paginator=Paginator(jobs, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context={
        'jobs': page_obj,
        'filter': filter,
    }
    return render(request,'job_list.html',context)

def job(request,id):
    job=get_object_or_404(Job,id=id)
    comments=Comment.objects.all()
    if request.method == 'POST':
        form = commentform(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = commentform()
    context = {
        'form': form,
        'job': job,
        'comments': comments,
    }
    return render(request, 'job_details.html', context)


def apply(request, id):
    job = get_object_or_404(Job, id=id)
    if request.method == 'POST':
        form = ApplyForm(request.POST, request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.job = job
            myform.save()
            return redirect("/")
    else:
        form = ApplyForm()
    context = {
        'form': form,
        'job': job,
    }
    return render(request, 'apply.html', context)




@login_required
def add_job(request):
    if request.method=='POST':
        
        form=JobForm(request.POST,request.FILES)
        if form.is_valid():
           
            myform=form.save(commit=False)
            myform.owner=request.user
            myform.save()
            return redirect('/')
    else:
        form = JobForm()
        
    context={
        'form':form,
    }
    return render(request,'add_job.html',context)

Accounts/templates/profile.html
{% extends "base.html" %}
{% load bootstrap4%}
{% block content %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>Your Profile</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <div class="job_sumary">
                    <div class="summery_header">
                        <div class="job_details_header">
                            <div class="single_jobs white-bg d-flex justify-content-between">
                                <div class="jobs_left d-flex align-items-center">
                                    <div class="thumb">
                                        {% if user.profile.image %}
                                        <img src="{{p.image.url}} " alt=""
                                            style="margin-left: -15px;height: 83px; weight: 37px;width: 81px;margin-top: -16px;">
                                        {% else %}
                        
                                        <img src="https://i.pinimg.com/474x/80/db/20/80db20fd3bb1d86ce32c2aec8c901efe.jpg" alt=""
                                            style="margin-left: -15px;height: 83px; weight: 37px;width: 81px;margin-top: -16px;">
                        
                                        {% endif %}
                        
                                    </div>

                                    <h3>{{p.user.first_name}} {{p.user.last_name}}</h3>
                                </div>
                            </div>
                            <div class="single_jobs white-bg d-flex justify-content-between"></div>
                                <div class="job_content">
                                    <ul>
                                        <li>username: <span>{{p.user}}</span></li>
                                        <li>full name: <span>{{p.user.first_name}} {{p.user.last_name}}</span></li>
                                        <li>email: <span>{{p.user.email}}</span></li>
                                        <li>phone: <span>{{p.phone}}</span></li>
                                        <li>adrrese: <span>{{p.address}}</span></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="single_jobs white-bg d-flex justify-content-between"></div>
                                <div class="descript_wrap white-bg">
                                    <div class="single_wrap">
                                
                                        <h4>Your biographie</h4>
                                        <p>{{p.biographie}}</p>
                                    </div>
                                </div>
                            </div>
                            <a class="boxed-btn3 w-100" href="{% url 'Accounts:edite_profile' %}">Edite profile</a>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content%}

Accounts/templates/signup.html
{% extends "base.html" %}
{% load bootstrap4%}
{% block content %}

<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>Login</h3>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="container">
        <div class="row">
            <div class="col-lg-10">
                {% csrf_token %}
                <form method="post" class="form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    
                    <button type="submit" class="boxed-btn3 w-100">Sign Up</button>
                    <br>
                    <br>
                </form>
                
            </div>
        </div>

    </div>
</div>

{% endblock %}

Job/templates/job_details.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}


<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{job.title}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="job_details_header">
                    <div class="single_jobs white-bg d-flex justify-content-between">
                        <div class="jobs_left d-flex align-items-center">
                            <div class="thumb">
                                <img src="{{job.image.url}} " alt="" style="margin-left: -15px;height: 83px; weight: 37px;width: 81px;margin-top: -16px;">
                            </div>
                            <div class="jobs_conetent">
                                <a href="#">
                                    <h4>{{job.title}}</h4>
                                </a>
                                <div class="links_locat d-flex align-items-center">
                                    <div class="location">
                                        <p> <i class="fa fa-map-marker"></i> {{job.city}},{{job.contry}}</p>
                                    </div>
                                    <div class="location">
                                        <p> <i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="jobs_right">
                            <div class="apply_now">
                                <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="descript_wrap white-bg">
                    <div class="single_wrap">
                        
                        <h4>Job description</h4>
                        <p>{{job.description}}</p>
                    </div>
                
                </div>
                <div class="descript_wrap white-bg">
                    
                
                </div>
                <div class="apply_job_form white-bg">
                    <h4>Apply for the job</h4>
                   
                    <a class="boxed-btn3 w-100" href="{% url 'Job:apply' job.id %} ">Apply Now</a>
                    <br>
                </div>
                <div class="apply_job_form white-bg">
                    <h4>Comments</h4>
                    {% for comment in comments %}
                    <h6>{{comment.full_name}} </h6>
                    <p>{{comment.comment}} </p>
                    
                    
                    
                    
                    {% endfor %}
                    

                </div>
               
                
                <div class="apply_job_form white-bg">
                    <h4>Add comment</h4>
                    <form method="POST" class="form" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        {% buttons %}
                        <button type="submit" class="boxed-btn3 w-100">Add</button>
                
                        {% endbuttons %}
                    </form>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="job_sumary">
                    <div class="summery_header">
                        <h3>Job Summery</h3>
                    </div>
                    <div class="job_content">
                        <ul>
                            <li>Published on: <span>{{job.published_at|date:"d M o "}}</span></li>
                            <li>Salary: <span> ${{job.salary}} </span></li>
                            <li>Location: <span>{{job.city}},{{job.contry}}</span></li>
                            <li>Job Nature: <span> {{job.job_type}}</span></li>
                        </ul>
                    </div>
                </div>
                <div class="share_wrap d-flex">
                    <span>Share at:</span>
                    <ul>
                        <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                    </ul>
                </div>
               
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png'%}">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css'%}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css'%}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css'%}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css'%}">

    <link rel="stylesheet" href="{% static 'css/stylee.css'%}">
    <!-- <link rel="stylesheet" href="{% static 'css/responsive.css'%}"> -->
</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="index.html">
                                        <img src="{% static 'img/logo.png'%}" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="{% url 'Job:job_list' %}">home</a></li>
                                            <li><a href="jobs.html">Browse Job</a></li>
                                            <li><a href="#">pages <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">
                                                    <li><a href="candidate.html">Candidates </a></li>
                                                    <li><a href="job_details.html">job details </a></li>
                                                    <li><a href="elements.html">elements</a></li>
                                                </ul>
                                            </li>
                                            
                                            <li><a href="{% url 'Contact:contact' %}">Contact</a></li>
                                            <li><a href="#">{{user.get_username}} <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">
                                                    <li><a href="{% url 'Accounts:profile'%}?next={{request.path}}">Profile</a></li>
                                                    <li><a href="{% url 'logout'%}?next={{request.path}}">Log out</a></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            
                            
                                
                            {% if user.is_authenticated %}
                                <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                    <div class="Appointment">

                                <div class="phone_num d-none d-xl-block">
                                    <li><a class="boxed-btn3" href=" {% url 'Job:add_job' %} ">Post a Job</a></li>
                                </div>
                                <div class="phone_num d-none d-xl-block">
                                    <li><a class="boxed-btn3" href="{% url 'logout'%}?next={{request.path}}">Log out</a></li>
                                </div>
                            
                            {% else %}
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                                <div class="phone_num d-none d-xl-block">
                                    <li><a class="boxed-btn3" href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                                </div>
                                <div class="phone_num d-none d-xl-block">
                                    <li><a class="boxed-btn3" href="{% url 'Accounts:signup'%}?next={{request.path}}">sign up</a></li>
                                </div>
                                        
                            {% endif %}
                            </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        </div>
        </div>
        
    </header>
    <!-- header-end -->

  

    
    {% block content %}
        
    {% endblock content %}
        

    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="{% static 'img/logo.png'%}" alt="">
                                </a>
                            </div>
                            <p>
                                aitzidan@gmail.com <br>
                                +212630307047 <br>
                                600/D, Green road, NewYork
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="ti-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
    
                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                            <h3 class="footer_title">
                                Company
                            </h3>
                            <ul>
                                <li><a href="#">About </a></li>
                                <li><a href="#"> Pricing</a></li>
                                <li><a href="#">Carrier Tips</a></li>
                                <li><a href="#">FAQ</a></li>
                            </ul>
    
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                            <h3 class="footer_title">
                                Category
                            </h3>
                            <ul>
                                <li><a href="#">Design & Art</a></li>
                                <li><a href="#">Engineering</a></li>
                                <li><a href="#">Sales & Marketing</a></li>
                                <li><a href="#">Finance</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                            <h3 class="footer_title">
                                Subscribe
                            </h3>
                            <form action="#" class="newsletter_form">
                                <input type="text" placeholder="Enter your mail">
                                <button type="submit">Subscribe</button>
                            </form>
                            <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                                luckily.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This
                            template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
                                href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->
    
    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static 'js/vendor/modernizr-3.5.0.mindd'%}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.mindd'%}"></script>
    <script src="{% static 'js/popper.mindd'%}"></script>
    <script src="{% static 'js/bootstrap.mindd'%}"></script>
    <script src="{% static 'js/owl.carousel.mindd'%}"></script>
    <script src="{% static 'js/isotope.pkgd.mindd'%}"></script>
    <script src="{% static 'js/ajax-formdd'%}"></script>
    <script src="{% static 'js/waypoints.mindd'%}"></script>
    <script src="{% static 'js/jquery.counterup.mindd'%}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.mindd'%}"></script>
    <script src="{% static 'js/scrollItdd'%}"></script>
    <script src="{% static 'js/jquery.scrollUp.mindd'%}"></script>
    <script src="{% static 'js/wow.mindd'%}"></script>
    <script src="{% static 'js/nice-select.mindd'%}"></script>
    <script src="{% static 'js/jquery.slicknav.mindd'%}"></script>
    <script src="{% static 'js/jquery.magnific-popup.mindd'%}"></script>
    <script src="{% static 'js/pluginsdd'%}"></script>
    <script src="{% static 'js/gijgo.mindd'%}"></script>
    
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- <script src="{% static 'js/gijgo.min.js' %}"></script> -->
    <script src="{% static 'js/range.js' %}"></script>
    
    <!--contact js-->
    <script src="{% static 'js/contactdd'%}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.mindd'%}"></script>
    <script src="{% static 'js/jquery.formdd'%}"></script>
    <script src="{% static 'js/jquery.validate.mindd'%}"></script>
    <script src="{% static 'js/mail-scriptdd'%}"></script>
    
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/maindd'%}"></script>
    </body>
    
    </html>